import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import LoginBtn from "./loginBtn";
import { cookies } from "next/headers";
import DarkMode from "./darkmode";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "백 엔드 테스트",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = cookies()
  let darkmode = (await cookieStore).get('darkmode')
  
  return (
    <html lang="ko">
      <body className={`${geistSans.variable} ${geistMono.variable}`} data-theme={darkmode?.value || 'light'}>
        <div className="navbar">
          <Link href="/">Choeforum</Link>
          <Link href="/list">List</Link>
          <LoginBtn></LoginBtn>
          <DarkMode></DarkMode>
        </div>
        {children}
      </body>
    </html>
  );
}
