version: '3.8'

services:
  nextjs-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: next-webeditor
    ports:
      - "80:80"
    restart: always
    volumes:
      - ./data:/app/data
      - ./public:/app/public
    networks:
      my_custom_network:
        ipv4_address: 172.20.0.2

networks:
  my_custom_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1 