from mypackage.module import datetime

class Model:
    status: str = None
    user_info: str = None 
    user_id: str = None
    user_name: str = None
    student_id: str = None
    character_type: str = None
    facial_expression1_url: bytes = None
    facial_expression2_url: bytes = None
    facial_expression3_url: bytes = None
    facial_expression4_url: bytes = None
    material_texture1_url: bytes = None
    material_texture2_url: bytes = None
    screenshot_image_url: bytes = None
    friend_name: str = None
    villain_name: str = None
    bg_name: str = None
    scenario_text: str = None
    motion_data1_url: bytes = None
    motion_data2_url: bytes = None
    motion_data3_url: bytes = None
    motion_data4_url: bytes = None
    motion_data5_url: bytes = None
    motion_data1: bytes = None
    motion_data2: bytes = None
    motion_data3: bytes = None
    motion_data4: bytes = None
    motion_data5: bytes = None
    video_file_url: bytes = None
    video_thumbnail_url: bytes = None
    message: str = None
    error_code: str = None
    timestamp: datetime = None

    def __init__(self):
        self.status = None
        self.user_info = None
        self.user_id = None
        self.user_name = None
        self.student_id = None
        self.character_type = None
        self.facial_expression1_url = None
        self.facial_expression2_url = None
        self.facial_expression3_url = None
        self.facial_expression4_url = None
        self.material_texture1_url = None
        self.material_texture2_url = None
        self.screenshot_image_url = None
        self.friend_name = None
        self.villain_name = None
        self.bg_name = None
        self.scenario_text = None
        self.motion_data1_url = None
        self.motion_data2_url = None
        self.motion_data3_url = None
        self.motion_data4_url = None
        self.motion_data5_url = None
        self.motion_data1 = None
        self.motion_data2 = None
        self.motion_data3 = None
        self.motion_data4 = None
        self.motion_data5 = None
        self.video_file_url = None
        self.video_thumbnail_url = None
        self.message = None
        self.error_code = None
        self.timestamp = None
