version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000" 
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    networks:
      - my_custom_network

networks:
  my_custom_network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.2.0/24

